type: 'DFT'
args:    
    sr: ${sampling_rate}
    n_fft: 400
    freq_bins: None
    freq_scale: 'no'
    center: True
    hop_length: ${hop_length}
    window: 'hann'
    pad_mode: 'reflect'
    fmin: null
    fmax: null