type: 'CNN_LINEAR'
args:
    norm_mode: 'imagewise'
    hidden_dim2: 256
    hidden_dim3: 128
    input_dim: 0 # will be overwritten inside the code
    output_dim: 0 # will be overwritten inside the code